### ISSUE TITLE
Process hangs with 100% CPU utilization

### ISSUE THREAD

**Issue by raphinesse** [codemodsquad/asyncify#24]
First of all thanks for the great work! This code mod seems to do a fantastic job from what I saw up until now.

Unfortunately there was a problem with one particular source file. To reproduce:

```
git clone https://github.com/apache/cordova-android.git
cd cordova-android
npm i jscodeshift @codemodsquad/asyncify
npx jscodeshift --verbose=2 -t node_modules/@codemodsquad/asyncify/index.js bin/templates/cordova/lib/check_reqs.js
```

There is no output from the process and it stays at 100% CPU utilization indefinitely (well, after 20 min or so I killed it).

**Comment by jedwards1211** [comment]
oh no, infinite loops 😅
okay, I'll look into it!

**Comment by jedwards1211** [comment]
@raphinesse btw you could avoid using `npx` in cases like this if you add `./node_modules/.bin` to your `PATH`

**Comment by jedwards1211** [comment]
Okay, the following code in `check_reqs.js` was obviously throwing it off.  `asyncify` was walking the scope bindings for `checkFn` to see if it got to a function declaration, but it was getting stuck in an infinite loop when it reached `checkFn`, because I am dumb 😃
So I made sure to exit that loop when the next step would be the same node, and it works now.

Just, FYI `asyncify` isn't smart enough to know that `checkFn` is definitely a function here even though developers can obviously tell.  If `asyncify` had found a function declaration named `checkFn` it would have unrolled `promise.then(checkFn)` into `await checkFn(await promise)`.

```js
    // Then execute requirement checks one-by-one
    return checkFns.reduce(function (promise, checkFn, idx) {
        // Update each requirement with results
        var requirement = requirements[idx];
        return promise.then(checkFn).then(function (version) {
            requirement.installed = true;
            requirement.metadata.version = version;
        }, function (err) {
            requirement.metadata.reason = err instanceof Error ? err.message : err;
        });
    }, Promise.resolve()).then(function () {
        // When chain is completed, return requirements array to upstream API
        return requirements;
    });
```

**Comment by raphinesse** [comment]
Thanks for the quick response and fix! Unfortunately I am still seeing an infinite loop when transforming `check_reqs.js` with 2.0.4 and 2.0.5. The loop occurs in `getBinding("checkFn")`. Here's the stack:
```
getBinding (index.js:880)
canDefinitelyInvoke (canDefinitelyInvoke.js? [sm]:16)
unwindThen (unwindThen.js? [sm]:73)
unwindPromiseChain (unwindPromiseChain.js? [sm]:46)
asyncifyFunction (asyncify.js? [sm]:37)
asyncify (asyncify.js? [sm]:98)
index (index.js? [sm]:42)
(anonymous) (Worker.js:157)
(anonymous) (graceful-fs.js:123)
readFileAfterClose (internal/fs/read_file_context.js:63)
```

**Comment by raphinesse** [comment]
**Update**: Running jscodeshift with `--no-babel` (i.e. _do not apply babeljs to the transform file_) fixed this for me. Probably a stale code cache somewhere :unamused: 

Thanks again for the quick fix and sorry for the bother with this cache issue.
